apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.app.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $.Values.app.label }}
  annotations:
    secret.reloader.stakater.com/reload: {{ $.Values.app.reloaderSecretName }}
spec:
  replicas: {{ $.Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.app.label }}
  template:
    metadata:
      labels:
        app: {{ $.Values.app.label }}
    spec:
      containers:
      - name: {{ $.Values.app.name }}
        image: {{ $.Values.app.image }}
        env:
        - name: ASPNETCORE_URLS
          value: "http://+;"
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $.Values.app.secretProviderClassName }}
            nodePublishSecretRef:
              name: secrets-store-creds 
