apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.svc.name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: {{ $.Values.svc.selector }}
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    name: "http"