name: Publish Docker image

on:
  workflow_dispatch:
        
jobs:
  build_and_push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: fblzs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./src/AzureCsiDriver.Application/Dockerfile
          no-cache: true
          push: true
          tags: |
            fblzs/azure-csi-driver-sample:v1
              
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} github
